version: "3.9"

services:
  backend:
    build: ./backend
    container_name: sentiment-backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./frontend
    container_name: sentiment-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
